### ISSUE TITLE
Documentation - Add a short notice for contributors

### ISSUE THREAD

**Issue by vdmitriyev** [dmarro89/dare-db#25]
Write and add a short notice for contributors. 
It should contain generic rules on how to make a PR, use discussions and issues. 
Should be added to README.md.

**Comment by dmarro89** [comment]
> Write and add a short notice for contributors. 
> 
> It should contain generic rules on how to make a PR, use discussions and issues. 
> 
> Should be added to README.md.

You're right.
I've starting today to write a contributions readme.

**Comment by vdmitriyev** [comment]
@dmarro89 I thought that I am going to do it, but if your want to overtake, it would be totally fine for me. Please find below version that I had written so far.

---
## How to contribute

All kind of contributions are welcome (e.g., code, ideas, bugs, comments, documetations, etc.)! 
If your found a bug open an issue and describe it shortly. If you want to add a feature, feel free to open an issue, assign it to yourself and make a pull request based on your issue. Note that discussion threads are used to discuss ideas. 

How to add a new feature using pull request:

1. Fork the repository (e.g., latest changes must be in ```develop``` branch)
```
git clone -b develop https://github.com/dmarro89/dare-db
```
2. Create a new branch for your feature. Use number of a newly created issue and keywodrs (e.g., ```10-implement-feature-ABC```)
```
git checkout -b 10-implement-feature-ABC
```
3. Add changes to the branch
```
git add .
```
4. Commit your changes 
```
git commit -am 'ADD: add new feature abc'
```
5. Push to the branch
```
git push origin 10-implement-feature-abc/your-feature-name
```
7. Open a pull request
8. Provide a short notice in the pull request accoding to the following structure:
	+ Added: ...
	+ Dependencied: ...
	+ Fixed: ...
---
