### ISSUE TITLE
Security - Implement basic authentication

### ISSUE THREAD

**Issue by vdmitriyev** [dmarro89/dare-db#33]
Maybe implementing a Basic Authentication would be enough as the first step to secure a database HTTPS endpoint. 
The implementation is much easier and should work well for the current case. Because currently, a database consist of a single data structure (key/value pairs) and most probably will be used by a single user.

For now, I would like to close issue with RBAC into backlog: https://github.com/dmarro89/dare-db/issues/7
Because, currently a single role and a single user in the database would be sufficient 

@dmarro89 what do you think?

**Comment by dmarro89** [comment]
Ok maybe we can start with a simple authentication but I would like to keep the RBAC discussion opened for future development

**Comment by vdmitriyev** [comment]
Totally agree with you. That is why is move the original issue to backlog and didn't close the discussion thread

**Comment by dmarro89** [comment]
> Totally agree with you. That is why is move the original issue to backlog and didn't close the discussion thread

Thanks

**Comment by dmarro89** [comment]
Hi @vdmitriyev, I'm sorry for the implementation delay but I'm on vacation. I hope to restart in the next week. Cheers

**Comment by vdmitriyev** [comment]
@dmarro89 Hi! Nice to hear from you. Being on vacation is a good think!

**Comment by vdmitriyev** [comment]
@dmarro89 would you close the ticket, because https://github.com/dmarro89/dare-db/pull/35 has been accepted and merged? Or you would like to wait, until the documentation, which reflects the changes in the PR will be written down?
