### ISSUE TITLE
Add JWT Authorization logic

### ISSUE THREAD

**Issue by dmarro89** [dmarro89/dare-db#36]

**Comment by TheInvincibleRalph** [comment]
Hi, I would love to work on this.

**Comment by dmarro89** [comment]
Hi @TheInvincibleRalph, thanks for your comment.
Could you please start with some review on the code?
It will be really appreciated.

Thanks

**Comment by dmarro89** [comment]
Hi @TheInvincibleRalph, sorry here's the [PR](https://github.com/dmarro89/dare-db/pull/37).
If you want, you could start to review the PR (I can add you as reviewer).
Then, there are other issues to work on for this project.
Feel free to take a look to the ongoing [discussions](https://github.com/dmarro89/dare-db/discussions) and partecipate.
Thanks

**Comment by TheInvincibleRalph** [comment]
Aright, @dmarro89

**Comment by vdmitriyev** [comment]
@dmarro89 
we also need to add information on `expirationTime` of a token (is now 5 minutes) to the documentation. 
Just writing this note in this issue, so it will not be forgotten/lost.

**Comment by dmarro89** [comment]
> @dmarro89 
> 
> we also need to add information on `expirationTime` of a token (is now 5 minutes) to the documentation. 
> 
> Just writing this note in this issue, so it will not be forgotten/lost. 

Thanks
