### ISSUE TITLE
Security - Implement RBAC to protect endpoints 

### ISSUE THREAD

**Issue by dmarro89** [dmarro89/dare-db#7]
- Let's start with a single kind of user -> only authenticated users can perform operations
- Define permissions -> currently just `read - write - delete`
- Authentication : let's start with JWT  (https://medium.com/@cheickzida/golang-implementing-jwt-token-authentication-bba9bfd84d60)
    - Create login endpoint and business logic / infrastructure to support login
    - Secure protected endpoints

**Comment by vdmitriyev** [comment]
Materials to consider for RBAC implementation:

* Building RBAC in Go - https://www.aserto.com/blog/building-rbac-in-go

**Comment by go-while** [comment]
i think we can authenticate peers by:

1) simple via ip address / cidr range
2) user/pass/anykey on every request
3) provide sessions with active/open connections for peers which are valid as long as connection is kept alive: less SYN paketstorm for opening new connections every request.

with any of the 3 options we can provide different access control levels, allow/deny specific commands for peers.

+ SSL to secure credentials (and transport)

Cheers!

**Comment by dmarro89** [comment]
Thanks @go-while

**Comment by vdmitriyev** [comment]
@go-while thanks for your ideas. Could I ask you to also reflect them in a discussion thread here (so we are going to have all related ideas in one place): https://github.com/dmarro89/dare-db/discussions/4

**Comment by vdmitriyev** [comment]
Moved to backlog. See https://github.com/dmarro89/dare-db/issues/33
